"use client"

import { Provider } from 'react-redux'
import './globals.css'
import { Inter } from 'next/font/google'
import { store } from '@/store/store'
import Nav from '@/components/Nav'
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';


export const metadata = {
  title: 'The Movie Database (TMDB)',
  description: 'generated by me',
}

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <Provider store={store}>
          {/* <Nav /> */}
          {children}
          <ToastContainer />
        </Provider> 
      </body>
    </html>
  )
}
